import { notFound } from "next/navigation";
import ClientProviders from "./providers/ClientProviders";

// const inter = Inter({ subsets: ["latin"] })

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// }
// const theme = createTheme({
//   /** Your theme override here */
// })

export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "jp" }, { locale: "mn" }];
}

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: any };
}) {
  console.log("layoutr render");
  let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    console.log(error);
    notFound();
  }

  console.log(messages, "(asdkasjd");

  return (
    <html lang={locale}>
      <body suppressHydrationWarning={true}>
        <ClientProviders params={{ locale }} messages={messages}>
          {children}
        </ClientProviders>
      </body>
    </html>
  );
}
